### ISSUE TITLE
VINS-Mono中的回环检测 | 一索哥传奇

### ISSUE THREAD

**Issue by zhehangT** [zhehangT/zhehangT.github.io#12]
http://zhehangt.win/2018/04/25/SLAM/VINS/VINSRelocalization/

**Comment by QLJX** [comment]
你好，对于地图融合我有问题想要询问一下。
我的目的是想要将第一次构建的地图1作为标准坐标系，在地图拼接之后，输出的位姿坐标都是在地图1的坐标系之下的数值。
一、重定位：如果可以在第二次启动vins后能够在地图1中重定位，就能实现我的目标。
你的文章中提到“加载地图1后，VINS-Mono 在启动之后并没有检测到与地图1的回环，即没有重定位成功，此时会新建一个地图，称为地图2”。我测试中发现，vins启动后需要初始化，即使在地图1的轨迹上初始化，也无法立即检测到回环。代码中有一部分序列检测，新的序列就是检测新到达的图像时间是否已经超过上一帧图像时间1s，如果时间太长则重新初始化，重新构建地图。那如何实现的重定位呢？
二、地图合并之后，坐标系仍然使用的地图2的坐标系，如何能在检测到回环后切换到地图1的坐标系中呢？
我是slam初学者，希望大神可以不吝赐教，万分感谢！

**Comment by zhehangT** [comment]
@QLJX 
1. 按照我的理解，目前的VINS并非对每一帧图像进行重定位，而是通过回环检测的方式把当前轨迹融合到已有的地图当中去。
2. 分别记录合并前和合并后地图1中的轨迹坐标，利用这个信息就可以得到地图1在合并前和合并后进行了怎么的T变换（包括旋转和平移），对地图2进行与T相反的变换，即转换到地图1中了。
